version: "3.8"

services:
  mariadb-kinn:
    build:
      context: .
      dockerfile: mariadb.Containerfile
    container_name: mariadb-kinn-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: habit_tracker_db
      MYSQL_USER: habit_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: unless-stopped

  # Service untuk PHP-Apache
  php-apache-kinn:
    build:
      context: .
      dockerfile: php-apache.Containerfile
    container_name: php-apache-kinn-container
    depends_on:
      - mariadb-kinn
    volumes:
      - ./app:/var/www/html:Z
    ports:
      - "8001:80"
    environment:
      DB_HOST: mariadb-kinn
      DB_NAME: habit_tracker_db
      DB_USER: habit_user
      DB_PASSWORD: userpassword
      DB_PORT: 3306
    networks:
      - app-network
    restart: unless-stopped

  # Service untuk PhpMyAdmin
  phpmyadmin-kinn:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-kinn-container
    depends_on:
      - mariadb-kinn
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb-kinn
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1G
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mariadb_data: # Definisi named volume untuk MariaDB

networks:
  app-network:
    driver: bridge
