version: "3.8"

services:
  # Service untuk MariaDB
  mariadb-kinn: # Diganti dari mariadb-namapanggilan
    build:
      context: . # Direktori tempat mariadb.Containerfile berada
      dockerfile: mariadb.Containerfile
    container_name: mariadb-kinn-container # Diganti dari mariadb-namapanggilan-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Ganti dengan password yang lebih aman
      MYSQL_DATABASE: habit_tracker_db # Nama database yang akan dibuat oleh MariaDB
      MYSQL_USER: habit_user # User untuk aplikasi PHP
      MYSQL_PASSWORD: userpassword # Password untuk user aplikasi PHP
    volumes:
      - mariadb_data:/var/lib/mysql # Volume untuk persistensi data MariaDB
    ports:
      - "3306:3306" # Mapping port MariaDB internal ke host (opsional jika hanya diakses service lain)
    networks:
      - app-network
    restart: unless-stopped

  # Service untuk PHP-Apache
  php-apache-kinn: # Diganti dari php-apache-namapanggilan
    build:
      context: . # Direktori tempat php-apache.Containerfile berada
      dockerfile: php-apache.Containerfile
    container_name: php-apache-kinn-container # Diganti dari php-apache-namapanggilan-container
    depends_on:
      - mariadb-kinn # Pastikan MariaDB berjalan dulu, diganti dari mariadb-namapanggilan
    volumes:
      - ./app:/var/www/html:Z # Mount direktori 'app' Anda (berisi file PHP) ke DocumentRoot Apache
    ports:
      - "8001:80" # Akses layanan HTTP pada port 8001 di host
    environment:
      DB_HOST: mariadb-kinn # Nama service MariaDB, bisa dijangkau dari service ini, diganti dari mariadb-namapanggilan
      DB_NAME: habit_tracker_db # Sama dengan MYSQL_DATABASE di service MariaDB
      DB_USER: habit_user # Sama dengan MYSQL_USER di service MariaDB
      DB_PASSWORD: userpassword # Sama dengan MYSQL_PASSWORD di service MariaDB
      DB_PORT: 3306
    networks:
      - app-network
    restart: unless-stopped

  # Service untuk PhpMyAdmin
  phpmyadmin-kinn: # Diganti dari phpmyadmin-namapanggilan
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-kinn-container # Diganti dari phpmyadmin-namapanggilan-container
    depends_on:
      - mariadb-kinn # PhpMyAdmin juga butuh MariaDB, diganti dari mariadb-namapanggilan
    ports:
      - "8081:80" # Akses PhpMyAdmin pada port 8081 di host (PENTING: port 8001 sudah dipakai php-apache-kinn)
        # PERHATIAN: Soal meminta port 8001, tapi ini akan konflik dengan php-apache.
        # Anda mungkin perlu mengklarifikasi ini. Jika harus 8001,
        # maka php-apache-kinn harus menggunakan port lain, atau salah satu tidak di-expose ke host
        # dan diakses melalui container lain jika diperlukan.
        # Untuk tujuan demonstrasi, saya menggunakan 8081 untuk phpMyAdmin.
        # Jika Anda *harus* menggunakan 8001 untuk phpMyAdmin, ubah port php-apache-kinn (misal ke 8000:80).
    environment:
      PMA_HOST: mariadb-kinn # Nama service MariaDB, diganti dari mariadb-namapanggilan
      PMA_PORT: 3306
      # PMA_USER: root (opsional, bisa login dengan root atau user yang dibuat)
      # PMA_PASSWORD: rootpassword (opsional)
      UPLOAD_LIMIT: 1G # Contoh penyesuaian lain jika perlu
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mariadb_data: # Definisi named volume untuk MariaDB

networks:
  app-network: # Definisi network kustom
    driver: bridge
